Document: debunk2
Title: Debian debunk2 Manual
Author: <insert document author here>
Abstract: This manual describes what debunk2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/debunk2/debunk2.sgml.gz

Format: postscript
Files: /usr/share/doc/debunk2/debunk2.ps.gz

Format: text
Files: /usr/share/doc/debunk2/debunk2.text.gz

Format: HTML
Index: /usr/share/doc/debunk2/html/index.html
Files: /usr/share/doc/debunk2/html/*.html

  
